[workspace]
resolver = "2"
members = [
    "crates/wecordy-api",
    "crates/wecordy-rest",
    "crates/wecordy-ws"
]

[workspace.package]
edition = "2024"
homepage = "https://github.com/wioenena/wecordy-rs"
repository = "https://github.com/wioenena/wecordy-rs"
license = "Apache-2.0"
rust-version = "1.93.0"

[workspace.dependencies]
http = { version = "1.4.0", default-features = false, features = ["std"] }
reqwest = { version = "0.13.3", default-features = false, features = ["rustls", "json"] }
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }
