[workspace]
resolver = "2"
members = ["crates/wecordy-api", "crates/wecordy-rest", "crates/wecordy-ws"]

[workspace.package]
edition = "2024"
rust-version = "1.93.0"
homepage = "https://github.com/wioenena/wecordy-rs"
repository = "https://github.com/wioenena/wecordy-rs"
license = "Apache-2.0"

[workspace.dependencies]
wecordy-api = { path = "crates/wecordy-api" }

futures-util = { version = "0.3.32" }
http = { version = "1.4.0", default-features = false, features = ["std"] }
reqwest = { version = "0.13.3", default-features = false, features = [
  "json",
  "rustls"
] }
rust_socketio = { version = "0.6.0", features = ["async"] }
serde = { version = "1.0.228", features = ["derive", "rc", "std"] }
serde_json = { version = "1.0.149", features = ["raw_value"] }
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }
tokio = { version = "1.52.2", features = ["macros", "net", "rt", "sync", "time"] }
tracing = "0.1.44"
url = { version = "2.5.8", default-features = false, features = ["std"] }

[profile.dev]
debug = "full"

[profile.release]
debug = "none"
