[workspace]

[package]
name = "wecordy-test"
version = "0.1.0"
edition = "2024"

[dependencies]
wecordy-rest = { path = "../crates/wecordy-rest" }
wecordy-api = { path = "../crates/wecordy-api", features = ["macros"] }

tokio = { version = "1.52.1", features = ["full"] }
anyhow = "1.0.102"
reqwest = "0.13.3"