[package]
name = "wecordy-rest"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "REST implementation for wecordy"
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
wecordy-api.workspace = true

reqwest.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
serde_json.workspace = true
